version: '3'
services:
  python-backend:
    build: .
    ports:
      - 8000:8000
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - 8001:80
    networks:
      - app-network
networks:
  app-network: